//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quickproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productid { get; set; }
        public string ProductName { get; set; }
        public int ProductNumber { get; set; }
        public string ProductProperties { get; set; }
        public List<Kategory> ProductKategories { get; set; }
    }
}
